services:
  web:
    build: .
    container_name: next13react18-web
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # DB接続情報（Nextから使う場合）
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=next_app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: next13react18-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: next_app
      MYSQL_USER: next_user
      MYSQL_PASSWORD: password
    ports:
      - "3253:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: next13react18-phpmyadmin
    restart: always
    ports:
      - "8022:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db

volumes:
  db_data: